version: "3"
services:
  jcservice:
    build: .
    ports:
      - 5432:8080
    links:
      - db
    environment:
      - PGPASSWORD=jcservice
      - PGDATABASE=jcservice
      - PGHOST=db:5432
      - PGUSER=postgres
    depends_on:
      - "db"
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=jcservice
      - POSTGRES_DB=jcservice
  
